# Generated by Django 3.1 on 2020-09-20 09:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('comments', '0002_auto_20200912_1101'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='category',
            new_name='topic',
        ),
    ]
