# Generated by Django 3.0.8 on 2020-09-08 05:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comments', '0002_auto_20200903_1705'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='description',
            field=models.TextField(default='This is a very old post that didn not have a description'),
            preserve_default=False,
        ),
    ]
