# Generated by Django 3.1 on 2020-09-20 10:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('comments', '0003_auto_20200920_0948'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='topic',
            new_name='category',
        ),
    ]
