# Generated by Django 3.0.8 on 2020-08-04 16:34

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('comments', '0003_auto_20200804_1614'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='comment_date',
            new_name='post_date',
        ),
        migrations.RenameField(
            model_name='reply',
            old_name='comment',
            new_name='post',
        ),
        migrations.AlterField(
            model_name='post',
            name='dislikes',
            field=models.ManyToManyField(related_name='post_dislike', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='post',
            name='likes',
            field=models.ManyToManyField(related_name='post_like', to=settings.AUTH_USER_MODEL),
        ),
    ]
