# Generated by Django 3.0.8 on 2020-08-05 09:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comments', '0006_reply'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='file',
            field=models.FileField(blank=True, null=True, upload_to='comments/file_uploades/'),
        ),
    ]
