# Generated by Django 3.0.8 on 2020-08-02 06:55

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('comments', '0007_comment_dislikes'),
    ]

    operations = [
        migrations.AddField(
            model_name='reply',
            name='dislikes',
            field=models.ManyToManyField(related_name='reply_dislike', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='reply',
            name='likes',
            field=models.ManyToManyField(related_name='reply_like', to=settings.AUTH_USER_MODEL),
        ),
    ]
