# Generated by Django 3.0.8 on 2020-08-05 09:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('comments', '0010_auto_20200805_0914'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='file',
            new_name='post_file',
        ),
    ]
