# Generated by Django 3.0.8 on 2020-08-08 05:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comments', '0011_auto_20200805_0944'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='post',
            index=models.Index(fields=['user', 'post_date'], name='comments_po_user_id_e9236f_idx'),
        ),
    ]
