# Generated by Django 3.0.8 on 2020-07-29 13:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('production', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='todo',
            name='note',
            field=models.TextField(blank=True, null=True),
        ),
    ]
