# Generated by Django 3.0.8 on 2020-08-27 12:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('production', '0002_auto_20200822_1756'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='todo',
            name='tag',
        ),
    ]
