# Generated by Django 3.0.8 on 2020-08-27 14:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('production', '0003_remove_todo_tag'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Tag',
        ),
    ]
