# Generated by Django 3.0.8 on 2020-08-30 10:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('production', '0006_auto_20200827_1715'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='feedback',
            name='user',
        ),
        migrations.AddField(
            model_name='feedback',
            name='name',
            field=models.CharField(default='Someone', max_length=30),
            preserve_default=False,
        ),
    ]
