# Generated by Django 3.0.8 on 2020-08-30 10:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('production', '0007_auto_20200830_1038'),
    ]

    operations = [
        migrations.AlterField(
            model_name='feedback',
            name='stars',
            field=models.CharField(choices=[('✭', '✭ Very Bad'), ('✭✭', '✭✭ Bad'), ('✭✭✭', '✭✭✭ Ok'), ('✭✭✭✭', '✭✭✭✭ Good'), ('✭✭✭✭✭', '✭✭✭✭✭ Excellent')], default='', max_length=15),
            preserve_default=False,
        ),
    ]
