# Generated by Django 3.0.8 on 2020-07-19 17:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('categories', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='about',
            field=models.CharField(default='Hey! This website is so cool and Free Of Distraction!', max_length=200),
        ),
    ]
