# Generated by Django 3.0.8 on 2020-08-26 11:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('categories', '0002_auto_20200826_1114'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='display',
            field=models.CharField(choices=[('primary', 'primary'), ('secondary', 'secondary'), ('success', 'success'), ('danger', 'danger'), ('warning', 'warning'), ('info', 'info'), ('light', 'light'), ('dark', 'dark')], default='dark', max_length=30),
        ),
    ]
