# Generated by Django 3.1 on 2020-09-20 09:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('comments', '0003_auto_20200920_0948'),
        ('categories', '0002_auto_20200916_1135'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Category',
            new_name='Topic',
        ),
    ]
