# Generated by Django 3.0.8 on 2020-07-20 16:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('categories', '0003_user_friends'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='about',
        ),
    ]
