# Generated by Django 3.0.8 on 2020-07-20 16:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('categories', '0004_remove_user_about'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='about',
            field=models.CharField(default='I love this website!', max_length=400),
            preserve_default=False,
        ),
    ]
