# Generated by Django 3.0.8 on 2020-07-19 14:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('categories', '0011_friendrequest'),
    ]

    operations = [
        migrations.DeleteModel(
            name='FriendRequest',
        ),
    ]
