# Generated by Django 3.0.8 on 2020-07-23 17:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('social', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chatbox',
            name='messages',
            field=models.TextField(null=True),
        ),
    ]
