# Generated by Django 3.0.8 on 2020-09-03 14:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('social', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='social/friend_message_images'),
        ),
        migrations.AddField(
            model_name='message',
            name='message_file',
            field=models.FileField(blank=True, null=True, upload_to='social_group_message_images'),
        ),
    ]
