# Generated by Django 3.0.8 on 2020-09-08 09:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('social', '0002_auto_20200903_1705'),
    ]

    operations = [
        migrations.AddField(
            model_name='groupmessage',
            name='file',
            field=models.FileField(blank=True, null=True, upload_to='social/group_files'),
        ),
        migrations.AddField(
            model_name='groupmessage',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='social/group_images'),
        ),
        migrations.AddField(
            model_name='groupmessage',
            name='video',
            field=models.FileField(blank=True, null=True, upload_to='social/group_videos'),
        ),
        migrations.AlterField(
            model_name='groupmessage',
            name='area',
            field=models.ForeignKey(blank=True, default='', null=True, on_delete=django.db.models.deletion.CASCADE, to='social.Area'),
        ),
        migrations.AlterField(
            model_name='groupmessage',
            name='message',
            field=models.TextField(blank=True, null=True),
        ),
    ]
