# Generated by Django 3.1 on 2020-09-18 04:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('social', '0002_remove_groupmessage_video'),
    ]

    operations = [
        migrations.AddField(
            model_name='groupmessage',
            name='video',
            field=models.FileField(blank=True, null=True, upload_to='social/group_videos'),
        ),
    ]
