# Generated by Django 3.0.8 on 2020-08-08 05:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('social', '0002_auto_20200803_1802'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='is_important',
            field=models.BooleanField(default=False),
        ),
    ]
