# Generated by Django 3.0.8 on 2020-07-23 17:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('social', '0002_auto_20200723_1754'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chatbox',
            name='messages',
            field=models.TextField(blank=True, null=True),
        ),
    ]
