# Generated by Django 3.0.8 on 2020-09-03 17:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('social', '0002_auto_20200903_1705'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='groupmessage',
            name='area',
        ),
        migrations.RemoveField(
            model_name='groupmessage',
            name='is_important',
        ),
        migrations.RemoveField(
            model_name='groupmessage',
            name='message',
        ),
    ]
