# Generated by Django 3.1 on 2020-08-21 04:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('social', '0002_auto_20200820_0615'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chatgroup',
            name='title',
            field=models.CharField(max_length=25),
        ),
    ]
