# Generated by Django 3.1 on 2020-09-24 12:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('social', '0002_auto_20200920_1159'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='groupmessage',
            name='is_important',
        ),
        migrations.RemoveField(
            model_name='message',
            name='is_important',
        ),
        migrations.RemoveField(
            model_name='notification',
            name='notification_type',
        ),
        migrations.AddField(
            model_name='notification',
            name='type',
            field=models.CharField(choices=[('friend_message', 'friend_message'), ('group_message', 'group_message'), ('comment_message', 'comment_message'), ('reply_message', 'reply_message'), ('invites', 'invites'), ('your_invites', 'your_invites')], default='friend_message', max_length=50),
        ),
    ]
