# Generated by Django 3.0.8 on 2020-07-28 15:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('social', '0002_auto_20200728_1501'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chatgroup',
            name='image',
            field=models.ImageField(default='categories_images/FocusTimeMedia.png', upload_to='group_images'),
        ),
    ]
