# Generated by Django 3.0.8 on 2020-08-31 14:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('social', '0003_auto_20200824_1841'),
    ]

    operations = [
        migrations.RenameField(
            model_name='groupmessage',
            old_name='sent_date',
            new_name='date',
        ),
        migrations.RenameField(
            model_name='grouprequest',
            old_name='sent_date',
            new_name='date',
        ),
        migrations.RenameField(
            model_name='message',
            old_name='sent_date',
            new_name='date',
        ),
    ]
