# Generated by Django 3.0.8 on 2020-08-08 18:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('social', '0003_message_is_important'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chatgroup',
            name='image',
            field=models.ImageField(default='categories_images/FocusTimeMedia.WebP', upload_to='group_images'),
        ),
    ]
