# Generated by Django 3.0.8 on 2020-09-08 10:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('social', '0003_auto_20200908_0912'),
    ]

    operations = [
        migrations.AddField(
            model_name='groupmessage',
            name='audio',
            field=models.ImageField(blank=True, null=True, upload_to='social/group_audio'),
        ),
    ]
