# Generated by Django 3.1 on 2020-09-18 05:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('social', '0003_groupmessage_video'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='message',
            name='audio',
        ),
        migrations.RemoveField(
            model_name='message',
            name='file',
        ),
        migrations.RemoveField(
            model_name='message',
            name='image',
        ),
        migrations.RemoveField(
            model_name='message',
            name='is_important',
        ),
        migrations.RemoveField(
            model_name='message',
            name='video',
        ),
    ]
