# Generated by Django 3.0.8 on 2020-08-14 12:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('social', '0003_auto_20200814_1225'),
    ]

    operations = [
        migrations.AddField(
            model_name='groupmessage',
            name='is_important',
            field=models.BooleanField(default=True),
        ),
    ]
