# Generated by Django 3.0.8 on 2020-08-16 06:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('social', '0003_notification_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='content',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
