# Generated by Django 3.1 on 2020-09-18 05:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('social', '0004_auto_20200918_0549'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='audio',
            field=models.ImageField(blank=True, null=True, upload_to='social/friend_message_audio'),
        ),
        migrations.AddField(
            model_name='message',
            name='file',
            field=models.FileField(blank=True, null=True, upload_to='social_group_message_images'),
        ),
        migrations.AddField(
            model_name='message',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='social/friend_message_images'),
        ),
        migrations.AddField(
            model_name='message',
            name='is_important',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='message',
            name='video',
            field=models.ImageField(blank=True, null=True, upload_to='social/friend_message_video'),
        ),
    ]
