# Generated by Django 3.0.8 on 2020-07-28 17:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('social', '0004_groupmessage'),
    ]

    operations = [
        migrations.RenameField(
            model_name='groupmessage',
            old_name='message',
            new_name='text',
        ),
    ]
