# Generated by Django 3.0.8 on 2020-09-09 07:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('social', '0004_groupmessage_audio'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='audio',
            field=models.ImageField(blank=True, null=True, upload_to='social/friend_message_audio'),
        ),
        migrations.AddField(
            model_name='message',
            name='video',
            field=models.ImageField(blank=True, null=True, upload_to='social/friend_message_video'),
        ),
    ]
