# Generated by Django 3.0.8 on 2020-09-03 14:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('social', '0004_auto_20200903_1444'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='message',
            name='file',
        ),
        migrations.AddField(
            model_name='message',
            name='message_file',
            field=models.FileField(blank=True, null=True, upload_to='social_group_message_images'),
        ),
    ]
