# Generated by Django 3.0.8 on 2020-08-14 12:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('social', '0004_groupmessage_is_important'),
    ]

    operations = [
        migrations.AlterField(
            model_name='groupmessage',
            name='is_important',
            field=models.BooleanField(default=False),
        ),
    ]
