# Generated by Django 3.1 on 2020-09-18 05:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('social', '0005_auto_20200918_0549'),
    ]

    operations = [
        migrations.AlterField(
            model_name='message',
            name='chat_box',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='social.chatbox'),
        ),
    ]
