# Generated by Django 3.0.8 on 2020-09-03 14:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('social', '0005_auto_20200903_1445'),
    ]

    operations = [
        migrations.RenameField(
            model_name='message',
            old_name='message_file',
            new_name='file',
        ),
    ]
