# Generated by Django 3.0.8 on 2020-08-15 12:39

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('social', '0005_auto_20200814_1227'),
    ]

    operations = [
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('notification_type', models.CharField(choices=[('important_friend_message', 'important_friend_message'), ('important_group_message', 'important_group_message'), ('normal_friend_message', 'normal_friend_message'), ('normal_group_message', 'normal_group_message'), ('comment_message', 'comment_message'), ('reply_message', 'reply_message'), ('friend_invite', 'friend_invite'), ('group_invite', 'group_invite'), ('accept_invite', 'accept_invite'), ('denied_invite', 'denied_invite')], max_length=50)),
                ('content', models.CharField(blank=True, max_length=200, null=True)),
                ('url', models.URLField(blank=True, null=True)),
                ('receiver', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notification_receiver', to=settings.AUTH_USER_MODEL)),
                ('sender', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notification_sender', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
