# Generated by Django 3.0.8 on 2020-07-24 13:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('social', '0005_chatbox_message_sender'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='chatbox',
            name='message_sender',
        ),
        migrations.RemoveField(
            model_name='chatbox',
            name='messages',
        ),
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sent_date', models.DateTimeField(auto_now_add=True)),
                ('messages', models.TextField()),
                ('chat_box', models.ManyToManyField(related_name='chat_box', to='social.ChatBox')),
            ],
        ),
    ]
