# Generated by Django 3.0.8 on 2020-07-28 17:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('social', '0005_auto_20200728_1728'),
    ]

    operations = [
        migrations.RenameField(
            model_name='groupmessage',
            old_name='text',
            new_name='message',
        ),
    ]
