# Generated by Django 3.1 on 2020-09-03 17:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('social', '0005_auto_20200903_1716'),
    ]

    operations = [
        migrations.AddField(
            model_name='groupmessage',
            name='area',
            field=models.ForeignKey(blank=True, default='', null=True, on_delete=django.db.models.deletion.CASCADE, to='social.area'),
        ),
        migrations.AddField(
            model_name='groupmessage',
            name='is_important',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='groupmessage',
            name='message',
            field=models.TextField(default=None),
            preserve_default=False,
        ),
    ]
