# Generated by Django 3.0.8 on 2020-08-16 06:57

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('social', '0005_auto_20200816_0651'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='receiver',
            field=models.ManyToManyField(default=None, related_name='notification_receiver', to=settings.AUTH_USER_MODEL),
        ),
    ]
