# Generated by Django 3.0.8 on 2020-09-02 05:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('social', '0005_area'),
    ]

    operations = [
        migrations.AlterField(
            model_name='area',
            name='messages',
            field=models.ManyToManyField(blank=True, related_name='message_area', to='social.GroupMessage'),
        ),
    ]
