# Generated by Django 3.1 on 2020-09-03 17:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('social', '0006_auto_20200903_1717'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='groupmessage',
            name='area',
        ),
        migrations.RemoveField(
            model_name='groupmessage',
            name='is_important',
        ),
        migrations.RemoveField(
            model_name='groupmessage',
            name='message',
        ),
    ]
