# Generated by Django 3.0.8 on 2020-07-24 13:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('social', '0006_auto_20200724_1345'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='message',
            name='chat_box',
        ),
        migrations.AddField(
            model_name='message',
            name='chat_box',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='chat_box', to='social.ChatBox'),
        ),
    ]
