# Generated by Django 3.0.8 on 2020-08-16 09:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('social', '0006_auto_20200816_0657'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='notification',
            name='image',
        ),
    ]
