# Generated by Django 3.0.8 on 2020-09-11 11:24

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('social', '0007_auto_20200911_1123'),
    ]

    operations = [
        migrations.AlterField(
            model_name='area',
            name='muted_users',
            field=models.ManyToManyField(blank=True, null=True, to=settings.AUTH_USER_MODEL),
        ),
    ]
