# Generated by Django 3.0.8 on 2020-08-16 10:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('social', '0007_remove_notification_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='notification_type',
            field=models.CharField(choices=[('important_friend_message', 'important_friend_message'), ('important_group_message', 'important_group_message'), ('normal_friend_message', 'normal_friend_message'), ('normal_group_message', 'normal_group_message'), ('comment_message', 'comment_message'), ('reply_message', 'reply_message'), ('invites', 'invites'), ('your_invites', 'your_invites')], max_length=50),
        ),
    ]
