# Generated by Django 3.0.8 on 2020-08-18 06:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('social', '0008_auto_20200816_1058'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chatgroup',
            name='image',
            field=models.ImageField(default='profile_images/DefaultUserImage.WebP', upload_to='social/group_images'),
        ),
    ]
