# Generated by Django 3.0.8 on 2020-09-06 06:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('social', '0008_auto_20200903_1724'),
    ]

    operations = [
        migrations.AddField(
            model_name='groupmessage',
            name='file',
            field=models.FileField(blank=True, null=True, upload_to='social/group_files'),
        ),
        migrations.AddField(
            model_name='groupmessage',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='social/group_images'),
        ),
        migrations.AlterField(
            model_name='groupmessage',
            name='message',
            field=models.TextField(blank=True, null=True),
        ),
    ]
