# Generated by Django 3.0.8 on 2020-07-24 14:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('social', '0008_message_message_sender'),
    ]

    operations = [
        migrations.RenameField(
            model_name='message',
            old_name='messages',
            new_name='message',
        ),
    ]
