# Generated by Django 3.1 on 2020-09-18 06:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('social', '0008_groupmessage_is_read'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='groupmessage',
            name='is_read',
        ),
    ]
