# Generated by Django 3.0.8 on 2020-09-08 08:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('social', '0009_auto_20200906_0657'),
    ]

    operations = [
        migrations.AddField(
            model_name='groupmessage',
            name='video',
            field=models.FileField(blank=True, null=True, upload_to='social/group_videos'),
        ),
    ]
