# Generated by Django 3.1 on 2020-09-19 04:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('social', '0009_remove_groupmessage_is_read'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='chatgroup',
            name='is_public',
        ),
    ]
