# Generated by Django 3.0.8 on 2020-08-22 17:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('categories', '0001_initial'),
        ('userpage', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='homepage_posts',
            field=models.ForeignKey(blank=True, default=2, null=True, on_delete=django.db.models.deletion.CASCADE, to='categories.Category'),
        ),
    ]
