# Generated by Django 3.0.8 on 2020-09-12 11:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userpage', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='hide_recommended_posts',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
    ]
