# Generated by Django 3.0.8 on 2020-07-22 11:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('userpage', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='about',
            new_name='bio',
        ),
    ]
