# Generated by Django 3.1 on 2020-08-21 04:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userpage', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='first_name',
            field=models.CharField(blank=True, max_length=150, verbose_name='first name'),
        ),
        migrations.AlterField(
            model_name='user',
            name='who_see_avatar',
            field=models.CharField(choices=[('none', 'No One'), ('friends', 'Friends only *Beta*'), ('everyone', 'Every One')], default='friends', max_length=30),
        ),
    ]
