# Generated by Django 3.1 on 2020-09-20 16:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('categories', '0001_initial'),
        ('userpage', '0002_remove_user_blocked_topics'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='blocked_topics',
            field=models.ManyToManyField(to='categories.Category'),
        ),
    ]
