# Generated by Django 3.0.8 on 2020-09-09 03:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userpage', '0002_auto_20200903_1712'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='blocked_topics',
        ),
        migrations.RemoveField(
            model_name='user',
            name='homepage_posts',
        ),
        migrations.AddField(
            model_name='user',
            name='email_code',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='homepage_hashtags',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='phone',
            field=models.CharField(blank=True, max_length=11, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='user',
            name='phone_code',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='first_name',
            field=models.CharField(blank=True, max_length=30, verbose_name='first name'),
        ),
    ]
