# Generated by Django 3.0.8 on 2020-08-19 03:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('categories', '0001_initial'),
        ('userpage', '0002_auto_20200816_1058'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='homepage_posts',
            field=models.ForeignKey(blank=True, default=True, on_delete=django.db.models.deletion.CASCADE, to='categories.Category'),
        ),
    ]
