# Generated by Django 3.0.8 on 2020-07-22 11:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userpage', '0002_auto_20200722_1115'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='avatar',
            field=models.ImageField(default='ƒDefaultUserImage.jpg', upload_to='profile_images'),
        ),
    ]
