# Generated by Django 3.0.8 on 2020-08-26 17:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('userpage', '0003_auto_20200824_1841'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='is_trusted',
        ),
    ]
