# Generated by Django 3.0.8 on 2020-09-09 11:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userpage', '0003_auto_20200909_0350'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='hide_recommended_posts',
            field=models.BooleanField(default=False),
        ),
    ]
