# Generated by Django 3.0.8 on 2020-08-27 11:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('userpage', '0004_remove_user_is_trusted'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='is_online',
        ),
    ]
