# Generated by Django 3.1 on 2020-09-16 09:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('userpage', '0004_auto_20200914_0629'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='fixed_navbar',
        ),
    ]
