# Generated by Django 3.0.8 on 2020-09-06 11:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userpage', '0004_remove_user_blocked_topics'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='email_code',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='phone_code',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
