# Generated by Django 3.0.8 on 2020-08-05 17:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('categories', '0001_initial'),
        ('userpage', '0004_user_allow_friend_request'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='blocked_categories',
            field=models.ManyToManyField(related_name='blocked_categories', to='categories.Category'),
        ),
        migrations.AddField(
            model_name='user',
            name='full_focus_mode',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='user',
            name='hide_comments',
            field=models.BooleanField(default=False),
        ),
    ]
