# Generated by Django 3.0.8 on 2020-08-14 17:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userpage', '0004_auto_20200814_1225'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='hide_posts_in_homepage',
            field=models.BooleanField(default=True),
        ),
    ]
