# Generated by Django 3.0.8 on 2020-09-12 04:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userpage', '0004_user_hide_recommended_posts'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='bio',
            field=models.CharField(blank=True, default='Hi there!', max_length=200, null=True),
        ),
    ]
