# Generated by Django 3.0.8 on 2020-08-19 05:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userpage', '0004_auto_20200819_0359'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='hide_posts_in_homepage',
            field=models.BooleanField(default=False),
        ),
    ]
