# Generated by Django 3.0.8 on 2020-08-27 17:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('categories', '0003_category_display'),
        ('userpage', '0005_remove_user_is_online'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='homepage_posts',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='categories.Category'),
        ),
    ]
