# Generated by Django 3.0.8 on 2020-07-26 06:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userpage', '0005_auto_20200722_1216'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='email_show',
            field=models.BooleanField(default=False),
        ),
    ]
