# Generated by Django 3.1 on 2020-09-16 11:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userpage', '0005_remove_user_fixed_navbar'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='default_home',
            field=models.CharField(choices=[('homepage', 'Homepage (default)'), ('followed_posts', 'Followed posts'), ('chat', 'Chat')], default=('homepage', 'Homepage (default)'), max_length=25),
        ),
    ]
