# Generated by Django 3.0.8 on 2020-08-05 17:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userpage', '0005_auto_20200805_1703'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='chat_only_mode',
            field=models.BooleanField(default=False),
        ),
    ]
