# Generated by Django 3.0.8 on 2020-07-26 06:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('userpage', '0006_user_email_show'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='email_show',
            new_name='show_email',
        ),
    ]
