# Generated by Django 3.0.8 on 2020-08-06 05:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('categories', '0001_initial'),
        ('userpage', '0006_user_chat_only_mode'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='blocked_categories',
            field=models.ManyToManyField(blank=True, related_name='blocked_categories', to='categories.Category'),
        ),
    ]
