# Generated by Django 3.1 on 2020-09-24 12:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('userpage', '0006_auto_20200923_1146'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='allow_comment_message',
            new_name='allow_comments_notifications',
        ),
        migrations.RenameField(
            model_name='user',
            old_name='allow_important_friend_messages',
            new_name='allow_friends_notifications',
        ),
        migrations.RenameField(
            model_name='user',
            old_name='allow_important_group_message',
            new_name='allow_groups_notifications',
        ),
        migrations.RenameField(
            model_name='user',
            old_name='allow_normal_friend_message',
            new_name='allow_replies_notifications',
        ),
        migrations.RemoveField(
            model_name='user',
            name='allow_normal_group_message',
        ),
        migrations.RemoveField(
            model_name='user',
            name='allow_reply_message',
        ),
    ]
