# Generated by Django 3.0.8 on 2020-08-15 13:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('userpage', '0007_auto_20200815_1320'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='full_focus_mode',
        ),
    ]
