# Generated by Django 3.0.8 on 2020-09-08 15:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('userpage', '0007_auto_20200908_1546'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='homepage_posts',
            new_name='homepage_hashtags',
        ),
    ]
