# Generated by Django 3.0.8 on 2020-07-26 07:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userpage', '0007_auto_20200726_0642'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='who_see_avatar',
            field=models.CharField(choices=[('none', 'No One'), ('friends', 'Friends Only'), ('everyone', 'Every One')], default='friends', max_length=30),
        ),
    ]
