# Generated by Django 3.0.8 on 2020-08-08 04:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userpage', '0007_auto_20200806_0556'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='max_posts',
            field=models.IntegerField(default=0),
        ),
    ]
