# Generated by Django 3.1 on 2020-09-17 05:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userpage', '0007_auto_20200916_1149'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='cover',
            field=models.ImageField(default='userpage/DefaultCover.jpg', upload_to='userpage/cover'),
        ),
    ]
