# Generated by Django 3.0.8 on 2020-08-08 05:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('userpage', '0008_user_max_posts'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='max_posts',
        ),
    ]
