# Generated by Django 3.0.8 on 2020-09-02 17:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userpage', '0008_auto_20200828_1553'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='who_see_avatar',
            field=models.CharField(choices=[('none', 'No One'), ('friends', 'Friends only'), ('everyone', 'Every One')], default='friends', max_length=30),
        ),
    ]
