# Generated by Django 3.0.8 on 2020-08-15 14:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('userpage', '0008_remove_user_full_focus_mode'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='allow_accept_invite',
            new_name='your_invites',
        ),
        migrations.RemoveField(
            model_name='user',
            name='allow_denied_invite',
        ),
    ]
