# Generated by Django 3.1 on 2020-09-17 08:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('userpage', '0008_user_cover'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='chat_only_mode',
        ),
    ]
