# Generated by Django 3.1 on 2020-09-17 08:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userpage', '0009_remove_user_chat_only_mode'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='cover',
            field=models.ImageField(default='userpage/cover/DefaultCover.jpg', upload_to='userpage/cover'),
        ),
    ]
