# Generated by Django 3.0.8 on 2020-08-08 06:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userpage', '0009_remove_user_max_posts'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='show_posts_in_homepage',
            field=models.BooleanField(default=False),
        ),
    ]
