# Generated by Django 3.1 on 2020-09-17 09:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('userpage', '0010_auto_20200917_0843'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='hide_followed_posts',
        ),
    ]
