# Generated by Django 3.0.8 on 2020-08-08 06:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userpage', '0011_auto_20200808_0646'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='show_posts_in_homepage',
            field=models.BooleanField(default=False),
        ),
    ]
