# Generated by Django 3.1 on 2020-09-18 20:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userpage', '0013_auto_20200918_1706'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='banned',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='user',
            name='who_add_group',
            field=models.CharField(choices=[('none', 'No One'), ('friends', 'Friends Only'), ('everyone', 'Every One')], default='everyone', max_length=30),
        ),
        migrations.AlterField(
            model_name='user',
            name='who_see_avatar',
            field=models.CharField(choices=[('none', 'No One'), ('friends', 'Friends only'), ('everyone', 'Every One')], default='everyone', max_length=30),
        ),
    ]
