# Generated by Django 3.1 on 2020-09-18 20:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userpage', '0014_auto_20200918_2018'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='banned',
        ),
        migrations.AlterField(
            model_name='user',
            name='who_add_group',
            field=models.CharField(choices=[('none', 'No One'), ('friends', 'Friends Only'), ('everyone', 'Every One')], default='friends', max_length=30),
        ),
        migrations.AlterField(
            model_name='user',
            name='who_see_avatar',
            field=models.CharField(choices=[('none', 'No One'), ('friends', 'Friends only'), ('everyone', 'Every One')], default='friends', max_length=30),
        ),
    ]
