# Generated by Django 3.1 on 2020-09-18 20:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userpage', '0015_auto_20200918_2022'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='company_name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='website',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='who_add_group',
            field=models.CharField(choices=[('none', 'No One'), ('friends', 'Friends Only'), ('everyone', 'Every One')], default='everyone', max_length=30),
        ),
        migrations.AlterField(
            model_name='user',
            name='who_see_avatar',
            field=models.CharField(choices=[('none', 'No One'), ('friends', 'Friends only'), ('everyone', 'Every One')], default='everyone', max_length=30),
        ),
    ]
