# Generated by Django 3.1 on 2020-09-19 06:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('userpage', '0017_auto_20200919_0413'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='company_name',
        ),
    ]
